version: '3.9'

#define services
services:
  web:
    container_name: simple-webapp
    build: .
    ports: 
       - "3000:3000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"